export const MOCK_NOTIFICATIONS = [
    {
        id: 1,
        type: 'GROUP_KICKED',
        title: '그룹에서 추방되었습니다',
        content: '관리자에 의해 "우리집 냉장고" 그룹에서 추방되었습니다.',
        isRead: false,
        groupId: 1,
        createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
    {
        id: 2,
        type: 'GROUP_PROMOTED',
        title: '관리자로 승격되었습니다',
        content: '"우리 회사 냉장고" 그룹의 관리자가 되었습니다.',
        isRead: false,
        groupId: 2,
        createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    },
    {
        id: 3,
        type: 'EXPIRY_SOON',
        title: '소비기한이 하루 남았습니다',
        content: '두부 (우리집 냉장고)의 소비기한이 내일까지입니다.',
        isRead: true,
        groupId: 1,
        relatedEntityId: 5,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    },
    {
        id: 4,
        type: 'NOTICE_CREATED',
        title: '새 공지사항이 등록되었습니다',
        content: '이번 주 금요일부터 냉장고 정리를 시작합니다. 개인 식품은 미리 챙겨가세요.',
        isRead: false,
        groupId: 3,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    },
    {
        id: 5,
        type: 'CLAIM_SUCCESS',
        title: '찜한 음식이 회원님의 것이 되었습니다',
        content: '찜해두셨던 계란 (12개)이 회원님의 보관함으로 이동했습니다.',
        isRead: true,
        groupId: 1,
        relatedEntityId: 7,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    },
    {
        id: 6,
        type: 'CLAIM_FAILED',
        title: '찜한 음식을 받지 못했습니다',
        content: '찜해두셨던 두부가 원소유자에 의해 소비/폐기되어 받을 수 없게 되었습니다.',
        isRead: false,
        groupId: 2,
        relatedEntityId: 9,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    },
];
